[tool.poetry]
name = "assignment-45"
version = "0.1.0"
description = ""
authors = ["aleezasaleem <aleezasaleem182@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.30.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
